offset_dict = {'pems0312': 1, 'pems0412': 2, 'pems0812': 3, 'la12': 4, 'pems0324': 5, 'pems0424': 5, 'pems0824': 5,
               'la24': 8, 'ETTh1_12': 9, 'ETTm1_12': 10, 'exchange_rate_12': 11, 'solar_12': 12, 'solar_24': 13,
               'ETTm1_24': 14, 'ETTh1_24': 15, 'exchange_rate_24': 16}
seed_dict = {'pems0312': '03_pretrain_noisy.log', 'pems0412': '04_pretrain_noisy.log',
             'pems0812': '08_pretrain_noisy.log', 'la12': 'la_pretrain_noisy.log',
             'pems0324': '03_pretrain_noisy_24.log',
             'pems0424': '04_pretrain_noisy_24.log', 'pems0824': '08_pretrain_noisy_24.log',
             'la24': 'la_pretrain_noisy24.log', 'ETTh1_12': 'ETTh1_pretrain_noisy.log',
             'ETTm1_12': 'ETTm1_pretrain_noisy.log', 'exchange_rate_12': 'exchange_rate_pretrain_noisy.log',
             'solar_12': 'solar_pretrain_noisy.log', 'solar_24': 'solar_pretrain_noisy24.log',
             'ETTm1_24': 'ETTm1_pretrain_noisy24.log', 'ETTh1_24': 'ETTh1_pretrain_noisy24.log',
             'exchange_rate_24': 'exchange_rate_pretrain_noisy24.log'}
ts2vec_embedding_dict = {'pems0312': 'pems/PEMS03/12_ts2vec_task_feature.npy',
                         'pems0412': 'pems/PEMS04/12_ts2vec_task_feature.npy',
                         'pems0812': 'pems/PEMS08/12_ts2vec_task_feature.npy',
                         'pems0712': 'pems/PEMS07/12_ts2vec_task_feature.npy',
                         'la12': 'METR-LA/metr-la/12_ts2vec_task_feature.npy',
                         'pems0324': 'pems/PEMS03/24_ts2vec_task_feature.npy',
                         'pems0424': 'pems/PEMS04/24_ts2vec_task_feature.npy',
                         'pems0824': 'pems/PEMS08/24_ts2vec_task_feature.npy',
                         'la24': 'METR-LA/metr-la/24_ts2vec_task_feature.npy',
                         'ETTh1_12': 'ETT-small/ETTh1/12_ts2vec_task_feature.npy',
                         'ETTm1_12': 'ETT-small/ETTm1/12_ts2vec_task_feature.npy',
                         'exchange_rate_12': 'exchange_rate/exchange_rate/12_ts2vec_task_feature.npy',
                         'solar_12': 'solar/solar_AL/12_ts2vec_task_feature.npy',
                         'solar_24': 'solar/solar_AL/24_ts2vec_task_feature.npy',
                         'ETTm1_24': 'ETT-small/ETTm1/24_ts2vec_task_feature.npy',
                         'ETTh1_24': 'ETT-small/ETTh1/24_ts2vec_task_feature.npy',
                         'exchange_rate_24': 'exchange_rate/exchange_rate/24_ts2vec_task_feature.npy',
                         'ETTh2_12': 'ETT-small/ETTh2/12_ts2vec_task_feature.npy',
                         'ETTm2_12': 'ETT-small/ETTm2/12_ts2vec_task_feature.npy'}

statistical_embedding_dict = {'pems0312': 'pems/PEMS03/12_embedding_feature.npy',
                              'pems0412': 'pems/PEMS04/12_embedding_feature.npy',
                              'pems0812': 'pems/PEMS08/12_embedding_feature.npy',
                              'pems0712': 'pems/PEMS07/12_embedding_feature.npy',
                              'la12': 'METR-LA/metr-la/12_embedding_feature.npy',
                              'pems0324': 'pems/PEMS03/24_embedding_feature.npy',
                              'pems0424': 'pems/PEMS04/24_embedding_feature.npy',
                              'pems0824': 'pems/PEMS08/24_embedding_feature.npy',
                              'la24': 'METR-LA/metr-la/24_embedding_feature.npy',
                              'ETTh1_12': 'ETT-small/ETTh1/12_embedding_feature.npy',
                              'ETTm1_12': 'ETT-small/ETTm1/12_embedding_feature.npy',
                              'exchange_rate_12': 'exchange_rate/exchange_rate/12_embedding_feature.npy',
                              'solar_12': 'solar/solar_AL/12_embedding_feature.npy',
                              'solar_24': 'solar/solar_AL/24_embedding_feature.npy',
                              'ETTm1_24': 'ETT-small/ETTm1/24_embedding_feature.npy',
                              'ETTh1_24': 'ETT-small/ETTh1/24_embedding_feature.npy',
                              'exchange_rate_24': 'exchange_rate/exchange_rate/24_embedding_feature.npy',
                              'ETTh2_12': 'ETT-small/ETTh2/12_embedding_feature.npy',
                              'ETTm2_12': 'ETT-small/ETTm2/12_embedding_feature.npy'}
